### ISSUE TITLE
Implement Initial RPC Parser Async Module

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/RPCParser#1]
### Tasks
- [ ] Initialization (logging)
- [ ] Add submodule that parses RPCs from raw data, creates RPC Objects
- [ ] Add transaction, stream IDs submodule
- [ ] Add timing submodule

**Comment by mfuroyama** [comment]
Moved to RPC Monitor
